### PR TITLE
Task 2

### PR DESCRIPTION
**Pull request by WizzyWu**
## Outputs:
- https://d29qcu9ke2ed75.cloudfront.net/ - CloudFront distribution domain name
- http://popov-js-aws-course.s3-website-eu-west-1.amazonaws.com/ - S3 Static site host

## What was done:
- Task 2.1 Manual Deployment
    * In the AWS Console created and configured an S3 bucket.
    * Builded and manually uploaded the MyShop! app to the created S3 bucket. Checked.
    * Created a CloudFront distribution for my app. Checked.
- Task 2.2 Automated Deployment
    * Added and configure serverless and serverless-finch plugins.
    * Manually created CloudFront invalidation.
    * Destroyed the created AWS infrastructure.
    * Added and configured serverless-single-page-app-plugin. * Added necessary npm script to build, upload, and invalidate app source code.
    * Tested automated deployment.
- Task 2.3
    * Stored links to CloudFront URL and S3-website in README.md file.
    * Commited all my work to separate branch.

### CODE REVIEW

**Comment by qqil** [comment]
Looks good, but I think you missed something [here](https://github.com/WizzyWu/js-aws-course-vue/blob/98cb917d5116606f4710c42f858305df29196d5c/serverless.yml#L34).

I can see that there is no direct access to S3 bucket, but looks like it was restricted manually. Can you confirm this?

**Comment by WizzyWu** [comment]
> Looks good, but I think you missed something [here](https://github.com/WizzyWu/js-aws-course-vue/blob/98cb917d5116606f4710c42f858305df29196d5c/serverless.yml#L34).
> 
> I can see that there is no direct access to S3 bucket, but looks like it was restricted manually. Can you confirm this?

Hello, @qqil, thank you for your check. S3 bucket that was configured manually was deleted during
Task 2.2 Automated Deployment (Destroyed the created AWS infrastructure).

I tried to deploy automatically with s3 bucket what was manually created, but it lead to an error, something like "Bucket with this name already exists". So i deleted it and this one is deployed automatically with Serverless Framework + Cloud Formation.

Access to S3 bucket is restricted by WebAppS3BucketPolicy, that allows access only to arn:aws:iam::cloudfront:user/CloudFront.

You can read about this identity here: 
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html

**Comment by qqil** [comment]
As far as I understood **WebAppS3BucketPolicy** is used to grant access to S3 Bucket for **CloudFront**.

I tried to run your code on my machine and here is what I see:

serverless-setup
serverless-setup2

**Comment by WizzyWu** [comment]
Hello @qqil , I changed AccessControl property for S3 to Private. Thank you for the tip.

**Pull request merged**
